package mdp.ingenieria.clinicagestion.vista;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class VistaAsociados {
    private JPanel mainPanel;
    private JTextField nomField;
    private JButton addButton;
    private JButton removeButton;
    private JTable table1;
    private JTextField dniField;
    private JTextField dirField;
    private JButton generateBtn;
    private JTextField apeField;
    private JTextField telField;
    private JTextField ciuField;

    private DefaultTableModel model;
    private Random random = new Random();

    public VistaAsociados() {
        String[] columnNames = {"Nombre", "DNI", "Domicilio"};
        Object[][] data = {};

        table1.setDefaultEditor(Object.class, null);

        model = new DefaultTableModel(data, columnNames);
        table1.setModel(model);
    }

    public void setActionListener(ActionListener actionListener) {
        nomField.addActionListener(actionListener);
        dniField.addActionListener(actionListener);
        dirField.addActionListener(actionListener);
        addButton.addActionListener(actionListener);
        removeButton.addActionListener(actionListener);
        generateBtn.addActionListener(actionListener);
    }

    public void addAsociado(String name, String id, String address) {
        model.addRow(new Object[]{name, id, address});
    }

    public void removeAsociado(int index) {
        if (index >= 0 && index < model.getRowCount()) {
            model.removeRow(index);
        }
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JTable getTable() {
        return table1;
    }

    public JTextField getTextField1() {
        return nomField;
    }

    public JTextField getTextField2() {
        return dniField;
    }

    public JTextField getTextField3() {
        return dirField;
    }

    public JButton getAddButton() {
        return addButton;
    }

    public JButton getRemoveButton() {
        return removeButton;
    }

    public JButton getGenerateBtn() {
        return generateBtn;
    }

    public DefaultTableModel getModel() {
        return model;
    }

    public List<JTextField> getAllTextFields() {
        return Arrays.asList(dniField, nomField, apeField, telField, ciuField, dirField);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setName("Page1");
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        generateBtn = new JButton();
        generateBtn.setActionCommand("Generar");
        generateBtn.setLabel("Generar");
        generateBtn.setText("Generar");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(generateBtn, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setAlignmentX(1.0f);
        scrollPane1.setAlignmentY(1.0f);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        table1 = new JTable();
        scrollPane1.setViewportView(table1);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(panel1, gbc);
        final JLabel label1 = new JLabel();
        label1.setName("");
        label1.setText("Page 1");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(label1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("DNI");
        panel2.add(label2, BorderLayout.NORTH);
        dniField = new JTextField();
        dniField.setPreferredSize(new Dimension(150, 20));
        panel2.add(dniField, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Nombre");
        panel3.add(label3, BorderLayout.NORTH);
        nomField = new JTextField();
        nomField.setColumns(0);
        nomField.setPreferredSize(new Dimension(150, 20));
        panel3.add(nomField, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Apellido");
        panel4.add(label4, BorderLayout.NORTH);
        apeField = new JTextField();
        apeField.setColumns(0);
        apeField.setPreferredSize(new Dimension(150, 20));
        panel4.add(apeField, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel5, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Teléfono");
        panel5.add(label5, BorderLayout.NORTH);
        telField = new JTextField();
        telField.setColumns(0);
        telField.setPreferredSize(new Dimension(150, 20));
        panel5.add(telField, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel6, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Ciudad");
        panel6.add(label6, BorderLayout.NORTH);
        ciuField = new JTextField();
        ciuField.setColumns(0);
        ciuField.setPreferredSize(new Dimension(150, 20));
        panel6.add(ciuField, BorderLayout.CENTER);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.VERTICAL;
        panel1.add(panel7, gbc);
        final JLabel label7 = new JLabel();
        label7.setText("Dirección");
        panel7.add(label7, BorderLayout.NORTH);
        dirField = new JTextField();
        dirField.setPreferredSize(new Dimension(150, 20));
        panel7.add(dirField, BorderLayout.CENTER);
        addButton = new JButton();
        addButton.setText("Añadir");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(addButton, gbc);
        removeButton = new JButton();
        removeButton.setText("Eliminar");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(removeButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
