package mdp.ingenieria.clinicagestion.vista;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Objects;

public class VistaBase {
    private JPanel mainPanel;
    private JButton page1Btn;
    private JButton page2Btn;

    private JPanel contentPanel;

    private VistaAsociados vista1;
    private VistaConfiguracion vista2;
    private VistaSimulacion vista3;
    private CardLayout cardLayout;

    public VistaBase() {
        JFrame frame = new JFrame("Clinica GUI");

        setupFrame(frame);
        setupContent();

        frame.setVisible(true);
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    private void setupFrame(JFrame frame) {
        frame.setContentPane(mainPanel); // agrega la base al JFrame
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.pack(); // configura el tamaño mínimo de la interfaz en base a sus componentes
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
    }

    private void setupContent() {
        vista1 = new VistaAsociados();
        vista2 = new VistaConfiguracion();
        vista3 = new VistaSimulacion();

        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout); // la parte dinámica de la página

        contentPanel.add(vista1.getMainPanel(), "PAGE1");
        contentPanel.add(vista2.getMainPanel(), "PAGE2");
        contentPanel.add(vista3.getMainPanel(), "PAGE3");

        showPage("PAGE1"); // muestra la primera página
    }

    public void showPage(String page) {
        cardLayout.show(contentPanel, page);

        if (Objects.equals(page, "PAGE3")) {
            page1Btn.setEnabled(false);
            page2Btn.setEnabled(false);
        } else {
            page1Btn.setEnabled(true);
            page2Btn.setEnabled(true);
        }
    }

    public void setActionListener(ActionListener actionListener) {
        page1Btn.addActionListener(actionListener);
        page2Btn.addActionListener(actionListener);

        vista3.getStopBtn().addActionListener(actionListener);
    }

    public VistaAsociados getVista1() {
        return vista1;
    }

    public VistaConfiguracion getVista2() {
        return vista2;
    }

    public VistaSimulacion getVista3() {
        return vista3;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Clínica");
        panel1.add(label1, BorderLayout.WEST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.EAST);
        page1Btn = new JButton();
        page1Btn.setActionCommand("PAGE1");
        page1Btn.setText("Page 1");
        panel2.add(page1Btn);
        page2Btn = new JButton();
        page2Btn.setActionCommand("PAGE2");
        page2Btn.setText("Page 2");
        panel2.add(page2Btn);
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        contentPanel.setMaximumSize(new Dimension(-1, -1));
        contentPanel.setPreferredSize(new Dimension(-1, -1));
        mainPanel.add(contentPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
