package mdp.ingenieria.clinicagestion.view;

import mdp.ingenieria.clinicagestion.controller.IVistaConfiguracion;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class VistaConfiguracion implements IVistaConfiguracion {
    private JPanel mainPanel;
    private JButton startBtn;
    private JTextField textField1;
    private JTextField textField2;
    private JCheckBox generarCheckBox;

    private int numAsoc = -1;
    private int numReq  = -1;
    private boolean isGenerated = false;

    /**
     * Registra el ActionListener que se ejecutará cuando se presione el botón de inicio
     * o cuando se interactúe con los campos de texto.
     * En el caso del botón, antes de delegar al listener, se validan y parsean los valores.
     *
     * <b>pre:</b> actionListener no debe ser null <br>
     * <b>post:</b> el listener queda asociado a startBtn y a los campos de texto
     *
     * @param actionListener manejador de acciones que se invocará al iniciar la simulación
     */
    @Override
    public void setActionListener(ActionListener actionListener) {
        startBtn.addActionListener(e -> {
            try {
                numAsoc = Integer.parseInt(textField1.getText().trim());
                numReq = Integer.parseInt(textField2.getText().trim());
                isGenerated = generarCheckBox.isSelected();

                if (numAsoc <= 0 || numReq <= 0)
                    popupError("Los números deben ser positivos");
                else
                    actionListener.actionPerformed(e);

            } catch (NumberFormatException exc) {
                popupError("Números inválidos");
            }
        });

        textField1.addActionListener(actionListener);
        textField2.addActionListener(actionListener);
    }

    /**
     * Muestra un mensaje emergente de error.
     *
     * @param message texto a mostrar
     */
    @Override
    public void popupError(String message) {
        JOptionPane.showMessageDialog(
                null,
                message,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    /**
     * @return número de asociados ingresados
     */
    @Override
    public int getNumAsoc() {
        return numAsoc;
    }

    /**
     * @return número de acciones por asociado
     */
    @Override
    public int getNumReq() {
        return numReq;
    }

    /**
     * Indica si se seleccionó la opción de generar asociados automáticamente.
     *
     * @return true si se generarán asociados aleatorios, false en caso contrario
     */
    @Override
    public boolean getIsGenerated() {
        return isGenerated;
    }

    /**
     * @return panel prinicpal de la vista de configuración
     */
    public JPanel getMainPanel() {
        return mainPanel;
    }

    /**
     * @return primer campo de texto (número de asociados)
     */
    public JTextField getTextField1() {
        return textField1;
    }

    /**
     * @return segundo campo de texto (número de acciones)
     */
    public JTextField getTextField2() {
        return textField2;
    }

    /**
     * @return botón que dispara el inicio de la simulación
     */
    public JButton getStartBtn() {
        return startBtn;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setName("Page2");
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setName("");
        label1.setText("Page 2");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(label1, gbc);
        startBtn = new JButton();
        startBtn.setActionCommand("PAGE3");
        startBtn.setLabel("Simular");
        startBtn.setText("Simular");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(startBtn, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(panel1, gbc);
        textField1 = new JTextField();
        textField1.setPreferredSize(new Dimension(150, 20));
        panel1.add(textField1, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("Número de asociados");
        panel1.add(label2, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(panel2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Número de acciones");
        panel2.add(label3, BorderLayout.NORTH);
        textField2 = new JTextField();
        textField2.setPreferredSize(new Dimension(150, 20));
        panel2.add(textField2, BorderLayout.CENTER);
        generarCheckBox = new JCheckBox();
        generarCheckBox.setText("Generar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        mainPanel.add(generarCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
