package mdp.ingenieria.clinicagestion.view;

import mdp.ingenieria.clinicagestion.controller.IVista;
import mdp.ingenieria.clinicagestion.controller.IVistaConfiguracion;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class VistaConfiguracion implements IVistaConfiguracion {
    private JPanel mainPanel;
    private JButton startBtn;
    private JTextField textField1;
    private JTextField textField2;

    private int numAsoc = -1;
    private int numReq  = -1;

    @Override
    public void setActionListener(ActionListener actionListener) {
        startBtn.addActionListener(e -> {
            try {
                numAsoc = Integer.parseInt(textField1.getText().trim());
                numReq  = Integer.parseInt(textField2.getText().trim());

                actionListener.actionPerformed(e);

            } catch (NumberFormatException exc) {
                popupError("Números inválidos");
            }
        });

        textField1.addActionListener(actionListener);
        textField2.addActionListener(actionListener);
    }

    @Override
    public void popupError(String message) {
        JOptionPane.showMessageDialog(
                null,
                message,
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
    }

    @Override
    public int getNumAsoc() {
        return numAsoc;
    }

    @Override
    public int getNumReq() {
        return numReq;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JTextField getTextField1() {
        return textField1;
    }

    public JTextField getTextField2() {
        return textField2;
    }

    public JButton getStartBtn() {
        return startBtn;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setName("Page2");
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JLabel label1 = new JLabel();
        label1.setName("");
        label1.setText("Page 2");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(label1, gbc);
        startBtn = new JButton();
        startBtn.setActionCommand("PAGE3");
        startBtn.setLabel("Simular");
        startBtn.setText("Simular");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(5, 5, 5, 5);
        mainPanel.add(startBtn, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(panel1, gbc);
        textField1 = new JTextField();
        textField1.setPreferredSize(new Dimension(150, 20));
        panel1.add(textField1, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("Número de asociados");
        panel1.add(label2, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(panel2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Número de acciones");
        panel2.add(label3, BorderLayout.NORTH);
        textField2 = new JTextField();
        textField2.setPreferredSize(new Dimension(150, 20));
        panel2.add(textField2, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
