package mdp.ingenieria.clinicagestion.view;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;

public class VistaSimulacion {
    private JPanel mainPanel;
    private JButton stopBtn;
    private JPanel panel1;
    private JPanel panel2;
    private JButton maintenanceBtn;
    private JLabel ambulanceLbl;

    String[] states = {
            "Tranquilito en casa",
            "Llamando ambulancia",
            "En traslado",
            "En tratamiento"
    };

    Color[] colors = {
            Color.WHITE,
            new Color(180, 246, 100),
            new Color(255, 229, 143),
            new Color(246, 112, 100)
    };

    public VistaSimulacion() {
        panel1.setLayout(new BoxLayout(panel1, BoxLayout.Y_AXIS));
        panel2.setLayout(new BoxLayout(panel2, BoxLayout.Y_AXIS));
        ambulanceLbl.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(122, 138, 153), 1),
                BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
    }

    public void setActionListener(ActionListener actionListener) {
        maintenanceBtn.addActionListener(actionListener);
    }

    public void addAsociado(String nya, int state) {
        FilaAsociado row = new FilaAsociado(nya, states[state]);
        panel1.add(row);
    }

    public void changeAsociadoState(int i, int state) {
        FilaAsociado row = (FilaAsociado) panel1.getComponent(i);
        row.updateState(states[state], colors[state]);
        row.setBackground(colors[state]);
    }

    public void addOperation(String msg) {
        JLabel label = new JLabel(msg);
        label.setAlignmentX(Component.RIGHT_ALIGNMENT);
        label.setBorder(new EmptyBorder(5, 5, 5, 5));
        panel2.add(label);
    }

    public void changeAmbulanceState(String state) {
        ambulanceLbl.setText(state);
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getMaintenanceBtn() {
        return maintenanceBtn;
    }

    public JButton getStopBtn() {
        return stopBtn;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setName("Page3");
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 30;
        gbc.ipady = 10;
        mainPanel.add(panel3, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Page 3");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel3.add(label1, gbc);
        maintenanceBtn = new JButton();
        maintenanceBtn.setText("Solicitar mantenimiento");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        panel3.add(maintenanceBtn, gbc);
        stopBtn = new JButton();
        stopBtn.setActionCommand("PAGE2");
        stopBtn.setText("Finalizar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel3.add(stopBtn, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane1, gbc);
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setBackground(new Color(-1));
        scrollPane1.setViewportView(panel1);
        final JScrollPane scrollPane2 = new JScrollPane();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(scrollPane2, gbc);
        panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        panel2.setBackground(new Color(-1));
        scrollPane2.setViewportView(panel2);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 0, 5, 0);
        mainPanel.add(panel4, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setText("Estado ambulancia");
        panel4.add(label2, BorderLayout.NORTH);
        ambulanceLbl = new JLabel();
        ambulanceLbl.setBackground(new Color(-1));
        ambulanceLbl.setHorizontalAlignment(0);
        ambulanceLbl.setMaximumSize(new Dimension(33, 34));
        ambulanceLbl.setOpaque(true);
        ambulanceLbl.setPreferredSize(new Dimension(33, 34));
        ambulanceLbl.setText("Label");
        panel4.add(ambulanceLbl, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
