package mdp.ingenieria.clinicagestion.view;

import mdp.ingenieria.clinicagestion.controller.IVista;
import mdp.ingenieria.clinicagestion.controller.IVistaBase;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.Objects;

public class VistaBase implements IVistaBase {
    private JPanel mainPanel;
    private JButton page1Btn;
    private JButton page2Btn;

    private JPanel contentPanel;

    private VistaAsociados vista1;
    private VistaConfiguracion vista2;
    private VistaSimulacion vista3;
    private CardLayout cardLayout;

    /**
     * Construye la vista base, inicializando el JFrame principal
     * y cargando las vistas internas.
     *
     * <b>post:</b> la ventana queda visible y en la página inicial
     */
    public VistaBase() {
        JFrame frame = new JFrame("Clinica GUI");

        setupFrame(frame);
        setupContent();

        frame.setVisible(true);
    }

    /**
     * Devuelve el panel contenedor donde se muestran las distintas páginas.
     *
     * @return panel central administrado por CardLayout
     */
    public JPanel getContentPanel() {
        return contentPanel;
    }

    /**
     * Configura el JFrame principal usando el mainPanel como contenido.
     *
     * <b>pre:</b> frame no debe ser null <br>
     * <b>post:</b> el frame queda inicializado con tamaño, cierre y contenido
     *
     * @param frame ventana principal de la aplicación
     */
    private void setupFrame(JFrame frame) {
        frame.setContentPane(mainPanel); // agrega la base al JFrame
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // frame.pack(); // configura el tamaño mínimo de la interfaz en base a sus componentes
        frame.setSize(800, 600);
        frame.setLocationRelativeTo(null);
    }

    /**
     * Crea las vistas internas y las registra en el panel de contenido.
     *
     * <b>post:</b> PAGE1, PAGE2 y PAGE3 quedan agregadas al CardLayout y se muestra PAGE1
     */
    private void setupContent() {
        vista1 = new VistaAsociados();
        vista2 = new VistaConfiguracion();
        vista3 = new VistaSimulacion();

        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout); // la parte dinámica de la página

        contentPanel.add(vista1.getMainPanel(), "PAGE1");
        contentPanel.add(vista2.getMainPanel(), "PAGE2");
        contentPanel.add(vista3.getMainPanel(), "PAGE3");

        showPage("PAGE1"); // muestra la primera página
    }

    /**
     * Muestra la página indicada en el panel de contenido.
     * Además, deshabilita los botones de navegación cuando se está en PAGE3.
     *
     * <b>pre:</b> page debe coincidir con alguna de las páginas registradas <br>
     * <b>post:</b> la vista solicitada queda visible en contentPanel
     *
     * @param page código de la página a mostrar (por ejemplo, "PAGE1", "PAGE2", "PAGE3")
     */
    public void showPage(String page) {
        cardLayout.show(contentPanel, page);

        if (Objects.equals(page, "PAGE3")) {
            page1Btn.setEnabled(false);
            page2Btn.setEnabled(false);
        } else {
            page1Btn.setEnabled(true);
            page2Btn.setEnabled(true);
        }
    }

    /**
     * Registra un ActionListener para los botones de navegación.
     *
     * <b>pre:</b> actionListener no debe ser null <br>
     * <b>post:</b> el listener queda asociado a page1Btn y page2Btn
     *
     * @param actionListener manejador de acciones de los botones
     */
    public void setActionListener(ActionListener actionListener) {
        page1Btn.addActionListener(actionListener);
        page2Btn.addActionListener(actionListener);
    }

    /**
     * Devuelve la vista correspondiente a la primera página (asociados).
     *
     * @return vista 1 como IVista
     */
    public IVista getVista1() {
        return vista1;
    }

    /**
     * Devuelve la vista correspondiente a la segunda página (configuración).
     *
     * @return vista 2 como IVista
     */
    public IVista getVista2() {
        return (IVista) vista2;
    }

    /**
     * Devuelve la vista correspondiente a la tercera página (simulación).
     *
     * @return vista 3 como IVista
     */
    public IVista getVista3() {
        return vista3;
    }
    
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Clínica");
        panel1.add(label1, BorderLayout.WEST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.EAST);
        page1Btn = new JButton();
        page1Btn.setActionCommand("PAGE1");
        page1Btn.setText("Page 1");
        panel2.add(page1Btn);
        page2Btn = new JButton();
        page2Btn.setActionCommand("PAGE2");
        page2Btn.setText("Page 2");
        panel2.add(page2Btn);
        contentPanel = new JPanel();
        contentPanel.setLayout(new BorderLayout(0, 0));
        contentPanel.setMaximumSize(new Dimension(-1, -1));
        contentPanel.setPreferredSize(new Dimension(-1, -1));
        mainPanel.add(contentPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
